/**
 * Hero type data - loaded from config/hero-types.json.
 *
 * DATA, not code (docs/conventions.md): generated by
 * tools/build-hero-types-data.mjs from the author's table and read ONCE at
 * startup, like config/skills.json (docs/decisions.md, 016).
 *
 * A hero type is a template: the player picks one, and it says which skills that
 * hero may learn and what each level costs. The actual skill levels a player
 * has chosen live in their save, not here (ADR 027, block 4).
 */

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const currentDir = path.dirname(fileURLToPath(import.meta.url));

/** <repo root>/config/hero-types.json - server/src/units is three levels deep. */
export const DEFAULT_HERO_TYPES_PATH = path.resolve(
  currentDir,
  '../../../config/hero-types.json',
);

/** Repo root, used only to print short paths in error messages. */
const REPO_ROOT = path.resolve(currentDir, '../../..');

/** Price of one skill at its three levels: [basic, advanced, expert]. */
export type SkillPrice = [number, number, number];

/** One hero template. */
export type HeroType = {
  /** Latin id, e.g. "rycar". */
  id: string;
  /** Russian display name, e.g. "Рыцарь". */
  name: string;
  /** "good" | "neutral" | "evil". */
  group: string;
  /** Russian name of the group, for the UI. */
  groupNameRu: string;
  /**
   * Skill id -> price per level. A skill that is NOT in this map is one the
   * hero simply cannot learn - that is different from a skill costing zero.
   */
  skills: Record<string, SkillPrice>;
};

/** The whole file. */
export type HeroTypesData = {
  heroCount: number;
  skillCount: number;
  skillIds: string[];
  groups: { id: string; nameRu: string }[];
  heroes: HeroType[];
};

function displayPath(filePath: string): string {
  const relativePath = path.relative(REPO_ROOT, filePath);

  return relativePath.startsWith('..') ? filePath : relativePath.split(path.sep).join('/');
}

function fail(where: string, message: string): never {
  throw new Error(where + ': ' + message);
}

/** Reads and validates the whole hero types file. Throws on anything broken. */
export function loadHeroTypes(filePath: string = DEFAULT_HERO_TYPES_PATH): HeroTypesData {
  const shown = displayPath(filePath);

  let raw: string;

  try {
    raw = readFileSync(filePath, 'utf8');
  } catch (error) {
    throw new Error(shown + ': не читается (' + (error as Error).message + ')');
  }

  let parsed: unknown;

  try {
    parsed = JSON.parse(raw);
  } catch (error) {
    throw new Error(shown + ': не разбирается как JSON (' + (error as Error).message + ')');
  }

  if (typeof parsed !== 'object' || parsed === null) {
    fail(shown, 'корень файла должен быть объектом');
  }

  const file = parsed as Record<string, unknown>;

  if (!Array.isArray(file.heroes)) {
    fail(shown, 'поле "heroes" должно быть массивом');
  }

  const knownSkills = new Set(Array.isArray(file.skillIds) ? (file.skillIds as string[]) : []);
  const seen = new Set<string>();

  const heroes = (file.heroes as unknown[]).map((rawHero, index) => {
    const where = shown + ', герой #' + (index + 1);

    if (typeof rawHero !== 'object' || rawHero === null) {
      fail(where, 'запись не объект');
    }

    const hero = rawHero as Record<string, unknown>;

    for (const key of ['id', 'name', 'group'] as const) {
      if (typeof hero[key] !== 'string' || (hero[key] as string).length === 0) {
        fail(where, 'поле "' + key + '" должно быть непустой строкой');
      }
    }

    if (seen.has(hero.id as string)) {
      fail(where, 'повторяющийся id героя: ' + hero.id);
    }

    seen.add(hero.id as string);

    const skills: Record<string, SkillPrice> = {};

    if (typeof hero.skills === 'object' && hero.skills !== null) {
      for (const [skillId, value] of Object.entries(hero.skills as Record<string, unknown>)) {
        if (knownSkills.size > 0 && !knownSkills.has(skillId)) {
          fail(where, 'навык "' + skillId + '" не объявлен в skillIds файла');
        }

        if (!Array.isArray(value) || value.length !== 3) {
          fail(where, 'навык "' + skillId + '": ожидались три цены');
        }

        const prices = value.map((price) => {
          if (typeof price !== 'number' || !Number.isFinite(price) || price <= 0) {
            fail(where, 'навык "' + skillId + '": цена должна быть положительным числом');
          }

          return price;
        }) as SkillPrice;

        if (prices[0] > prices[1] || prices[1] > prices[2]) {
          fail(where, 'навык "' + skillId + '": цены должны расти по уровням');
        }

        skills[skillId] = prices;
      }
    }

    return {
      id: hero.id as string,
      name: hero.name as string,
      group: hero.group as string,
      groupNameRu: typeof hero.groupNameRu === 'string' ? hero.groupNameRu : (hero.group as string),
      skills,
    };
  });

  return {
    heroCount: typeof file.heroCount === 'number' ? file.heroCount : heroes.length,
    skillCount: typeof file.skillCount === 'number' ? file.skillCount : 0,
    skillIds: Array.isArray(file.skillIds) ? (file.skillIds as string[]) : [],
    groups: Array.isArray(file.groups)
      ? (file.groups as HeroTypesData['groups'])
      : [],
    heroes,
  };
}

/** Finds a hero template by id, or undefined. */
export function findHeroType(data: HeroTypesData, heroId: string): HeroType | undefined {
  return data.heroes.find((hero) => hero.id === heroId);
}

/** Price of one skill level for a hero, or null when the hero cannot learn it. */
export function skillPrice(hero: HeroType, skillId: string, level: 1 | 2 | 3): number | null {
  const prices = hero.skills[skillId];

  if (!prices) {
    return null;
  }

  return prices[level - 1];
}

/** True when this hero may learn that skill at all. */
export function heroCanLearn(hero: HeroType, skillId: string): boolean {
  return hero.skills[skillId] !== undefined;
}

/** In-memory copy of the hero templates; null until loaded. */
let currentHeroTypes: HeroTypesData | null = null;

/** Stores the hero templates loaded at startup. */
export function setHeroTypes(data: HeroTypesData): void {
  currentHeroTypes = data;
}

/** The hero templates currently in memory. */
export function getHeroTypes(): HeroTypesData {
  if (currentHeroTypes === null) {
    throw new Error(
      'Данные типов героев не загружены: вызовите initHeroTypes() один раз при старте ' +
        'сервера (см. server/src/index.ts)',
    );
  }

  return currentHeroTypes;
}

/** Loads the hero templates once and keeps them in memory: the startup path. */
export function initHeroTypes(filePath: string = DEFAULT_HERO_TYPES_PATH): HeroTypesData {
  const data = loadHeroTypes(filePath);

  setHeroTypes(data);

  return data;
}
