/**
 * Unit data - loaded from config/units.json.
 *
 * Units are DATA, not code (docs/conventions.md, "Data vs code"): the file is
 * generated by tools/build-units-data.mjs from the author's table and read ONCE
 * at server startup, exactly like config/skills.json (docs/decisions.md, 016).
 *
 * IMPORTANT HONESTY RULE (ADR 027): abilities the battle engine does not
 * support are NOT faked. They stay inside `description`, and the UI shows them
 * as "not applied yet". A unit that says "flies" but does not fly would look
 * broken, so we never pretend.
 */

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import type { AbilityTag, UnitStats } from '@de-jija/shared';

const currentDir = path.dirname(fileURLToPath(import.meta.url));

/** <repo root>/config/units.json - server/src/units is three levels deep. */
export const DEFAULT_UNITS_PATH = path.resolve(currentDir, '../../../config/units.json');

/** Repo root, used only to print short paths in error messages. */
const REPO_ROOT = path.resolve(currentDir, '../../..');

/** One faction of units. Groups mirror the author's table. */
export type UnitRace = {
  /** Latin id, e.g. "castle". Referenced by UnitData.raceId. */
  id: string;
  /** "light" | "neutral" | "dark". */
  group: string;
  /** Russian display name, e.g. "Замок". */
  nameRu: string;
  /** How many units this faction contributes. */
  unitCount: number;
};

/** One unit as the game stores it: plain data, no behaviour. */
export type UnitData = {
  /** Latin id, unique across the whole file. */
  id: string;
  /** Russian display name, e.g. "Копейщики". */
  name: string;
  /** Combat stats. Same shape the battle engine already uses. */
  stats: UnitStats;
  /** Faction id this unit belongs to. */
  raceId: string;
  /** Cost of the first unit of this type, in charisma. */
  charisma: number;
  /** Growth factor of the recruitment price, e.g. 1.016. */
  charismaRatio: number;
  /** Pack size: how many units you get at once. */
  packSize: number;
  /** Ranged shots left, when the unit can shoot at distance. */
  shots?: number;
  /** Retaliations per round; 'unlimited' for units that answer every attack. */
  retaliationsPerRound?: number | 'unlimited';
  /** Only abilities the engine really applies. See the honesty rule above. */
  tags?: AbilityTag[];
  /** Original Russian description, including abilities not applied yet. */
  description?: string;
};

/** The whole file. */
export type UnitsData = {
  unitCount: number;
  raceCount: number;
  supportedTags: AbilityTag[];
  skippedRows: { row: number; faction: string; reason: string }[];
  races: UnitRace[];
  units: UnitData[];
};

/** Short, readable path for messages: config/units.json instead of C:\... */
function displayPath(filePath: string): string {
  const relativePath = path.relative(REPO_ROOT, filePath);

  return relativePath.startsWith('..') ? filePath : relativePath.split(path.sep).join('/');
}

/** Throws with a readable message; the server must not run on half-loaded data. */
function fail(where: string, message: string): never {
  throw new Error(where + ': ' + message);
}

/** Validates one unit record. Anything wrong here is a bug in the DATA file. */
function parseUnit(raw: unknown, where: string): UnitData {
  if (typeof raw !== 'object' || raw === null) {
    fail(where, 'запись юнита не объект');
  }

  const unit = raw as Record<string, unknown>;

  for (const key of ['id', 'name', 'raceId'] as const) {
    if (typeof unit[key] !== 'string' || (unit[key] as string).length === 0) {
      fail(where, 'поле "' + key + '" должно быть непустой строкой');
    }
  }

  const stats = unit.stats;

  if (typeof stats !== 'object' || stats === null) {
    fail(where, 'поле "stats" должно быть объектом чисел');
  }

  const rawStats = stats as Record<string, unknown>;

  for (const key of ['hp', 'attack', 'defense', 'speed', 'damageMin', 'damageMax'] as const) {
    const value = rawStats[key];

    if (typeof value !== 'number' || !Number.isFinite(value)) {
      fail(where, 'stats.' + key + ' должно быть числом, получено: ' + JSON.stringify(value));
    }
  }

  const damageMin = rawStats.damageMin as number;
  const damageMax = rawStats.damageMax as number;

  if (damageMin < 0 || damageMax < damageMin) {
    fail(where, 'диапазон урона некорректен: ' + damageMin + '-' + damageMax);
  }

  for (const key of ['charisma', 'charismaRatio', 'packSize'] as const) {
    const value = unit[key];

    if (typeof value !== 'number' || !Number.isFinite(value) || value <= 0) {
      fail(where, 'поле "' + key + '" должно быть положительным числом');
    }
  }

  if ((unit.charismaRatio as number) <= 1) {
    fail(where, 'charismaRatio должен быть больше 1, иначе цена не растёт');
  }

  const parsed: UnitData = {
    id: unit.id as string,
    name: unit.name as string,
    stats: rawStats as unknown as UnitStats,
    raceId: unit.raceId as string,
    charisma: unit.charisma as number,
    charismaRatio: unit.charismaRatio as number,
    packSize: unit.packSize as number,
  };

  if (unit.shots !== undefined) {
    if (typeof unit.shots !== 'number' || unit.shots <= 0) {
      fail(where, 'shots должно быть положительным числом, если поле есть');
    }

    parsed.shots = unit.shots;
  }

  if (unit.retaliationsPerRound !== undefined) {
    const value = unit.retaliationsPerRound;

    if (value !== 'unlimited' && (typeof value !== 'number' || value <= 0)) {
      fail(where, 'retaliationsPerRound должно быть числом или "unlimited"');
    }

    parsed.retaliationsPerRound = value as number | 'unlimited';
  }

  if (unit.tags !== undefined) {
    if (!Array.isArray(unit.tags) || unit.tags.length === 0) {
      fail(where, 'tags должно быть непустым массивом, если поле есть');
    }

    parsed.tags = unit.tags as AbilityTag[];
  }

  if (unit.description !== undefined) {
    if (typeof unit.description !== 'string') {
      fail(where, 'description должно быть строкой, если поле есть');
    }

    parsed.description = unit.description;
  }

  return parsed;
}

/** Reads and validates the whole units file. Throws on anything broken. */
export function loadUnits(filePath: string = DEFAULT_UNITS_PATH): UnitsData {
  const shown = displayPath(filePath);

  let raw: string;

  try {
    raw = readFileSync(filePath, 'utf8');
  } catch (error) {
    throw new Error(shown + ': не читается (' + (error as Error).message + ')');
  }

  let parsed: unknown;

  try {
    parsed = JSON.parse(raw);
  } catch (error) {
    throw new Error(shown + ': не разбирается как JSON (' + (error as Error).message + ')');
  }

  if (typeof parsed !== 'object' || parsed === null) {
    fail(shown, 'корень файла должен быть объектом');
  }

  const file = parsed as Record<string, unknown>;

  if (!Array.isArray(file.units)) {
    fail(shown, 'поле "units" должно быть массивом');
  }

  if (!Array.isArray(file.races)) {
    fail(shown, 'поле "races" должно быть массивом');
  }

  const raceIds = new Set<string>();
  const races: UnitRace[] = file.races.map((raw, index) => {
    const where = shown + ', фракция #' + (index + 1);

    if (typeof raw !== 'object' || raw === null) {
      fail(where, 'запись не объект');
    }

    const race = raw as Record<string, unknown>;

    if (typeof race.id !== 'string' || race.id.length === 0) {
      fail(where, 'поле "id" должно быть непустой строкой');
    }

    if (raceIds.has(race.id)) {
      fail(where, 'повторяющийся id фракции: ' + race.id);
    }

    raceIds.add(race.id);

    if (typeof race.nameRu !== 'string' || race.nameRu.length === 0) {
      fail(where, 'поле "nameRu" должно быть непустой строкой');
    }

    return {
      id: race.id,
      group: typeof race.group === 'string' ? race.group : 'unknown',
      nameRu: race.nameRu,
      unitCount: typeof race.unitCount === 'number' ? race.unitCount : 0,
    };
  });

  const unitIds = new Set<string>();
  const units = (file.units as unknown[]).map((raw, index) => {
    const unit = parseUnit(raw, shown + ', юнит #' + (index + 1));

    if (unitIds.has(unit.id)) {
      fail(shown, 'повторяющийся id юнита: ' + unit.id);
    }

    unitIds.add(unit.id);

    if (!raceIds.has(unit.raceId)) {
      fail(
        shown,
        'юнит "' + unit.name + '" ссылается на неизвестную фракцию: ' + unit.raceId,
      );
    }

    return unit;
  });

  return {
    unitCount: typeof file.unitCount === 'number' ? file.unitCount : units.length,
    raceCount: typeof file.raceCount === 'number' ? file.raceCount : races.length,
    supportedTags: Array.isArray(file.supportedTags)
      ? (file.supportedTags as AbilityTag[])
      : [],
    skippedRows: Array.isArray(file.skippedRows)
      ? (file.skippedRows as UnitsData['skippedRows'])
      : [],
    races,
    units,
  };
}

/**
 * Cost of hiring n units of one type, in charisma.
 *
 * From the author's table: the first unit costs `charisma`, every next unit is
 * `charismaRatio` times the previous one, and the total is the sum of the
 * progression rounded UP to a whole number:
 *
 *   C(n) = ceil(charisma / (ratio - 1) * (ratio^n - 1))
 *
 * Verified against the author's own check examples for Imps (38 / 1.0160):
 * C(1) = 38, C(2) = 77, C(6) = 238, C(106) = 10402.
 */
export function stackCost(unit: UnitData, count: number): number {
  if (!Number.isFinite(count) || count < 0) {
    throw new Error('count должен быть целым неотрицательным числом, получено: ' + count);
  }

  const n = Math.trunc(count);

  if (n === 0) {
    return 0;
  }

  const sum = (unit.charisma / (unit.charismaRatio - 1)) * (Math.pow(unit.charismaRatio, n) - 1);

  return Math.ceil(sum);
}

/** Finds a unit by id, or undefined. */
export function findUnit(data: UnitsData, unitId: string): UnitData | undefined {
  return data.units.find((unit) => unit.id === unitId);
}

/** Finds a faction by id, or undefined. */
export function findRace(data: UnitsData, raceId: string): UnitRace | undefined {
  return data.races.find((race) => race.id === raceId);
}

/** All units of one faction, in file order. */
export function unitsOfRace(data: UnitsData, raceId: string): UnitData[] {
  return data.units.filter((unit) => unit.raceId === raceId);
}

/** In-memory copy of the units; null until the server (or a test) loads them. */
let currentUnits: UnitsData | null = null;

/** Stores the units loaded at startup. */
export function setUnits(unitsData: UnitsData): void {
  currentUnits = unitsData;
}

/** The units currently in memory. */
export function getUnits(): UnitsData {
  if (currentUnits === null) {
    throw new Error(
      'Данные юнитов не загружены: вызовите loadUnits()/initUnits() один раз при старте ' +
        'сервера (см. server/src/index.ts)',
    );
  }

  return currentUnits;
}

/** Loads the units once and keeps them in memory: the normal startup path. */
export function initUnits(filePath: string = DEFAULT_UNITS_PATH): UnitsData {
  const unitsData = loadUnits(filePath);

  setUnits(unitsData);

  return unitsData;
}

